In [1]:
import pandas as pd
import numpy as np

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [2]:
def ds_prep(smi_list):
    char_array = []
    for smi in smi_list:
        char_list = [x for x in smi]
        char_array.append(char_list)
    #char_array = np.array(char_array)
    #char_array = np.reshape(char_array,(len(smi_list),1 , 1))
    return char_array

In [3]:
df = pd.read_csv('aspirin_like.csv')
df.drop_duplicates('Smiles',inplace = True)
df.shape

(269, 12)

In [4]:
smiles = df['Smiles'].to_list()
for i in range(len(smiles)): #add newline to each SMILES string
    smiles[i] = smiles[i]+'\n'
smiles[1]

'C1=CC=C(C(=C1)C(=O)O)O[N+](=O)[O-]\n'

In [5]:
max_smi, min_smi = 0, len(smiles[0])

for smi in smiles:
    if len(smi) > max_smi:
        max_smi = len(smi)
    if len(smi) < min_smi:
        min_smi = len(smi)
max_smi, min_smi

(38, 18)

In [6]:
features = []
labels = []

smi_len = 10 # characters from Smiles

for smi in smiles:
    for i in range(smi_len, len(smi)):
        seq = smi[i-smi_len:i + 1]
        features.append(seq[:-1])
        labels.append(seq[1:])
        
features[:5], labels[:5]

(['CC(=O)OC1=', 'C(=O)OC1=C', '(=O)OC1=CC', '=O)OC1=CC=', 'O)OC1=CC=C'],
 ['C(=O)OC1=C', '(=O)OC1=CC', '=O)OC1=CC=', 'O)OC1=CC=C', ')OC1=CC=CC'])

In [7]:
raw_dataset = tf.data.Dataset.from_tensor_slices(smiles)

In [8]:
preprocess = layers.TextVectorization(standardize = None, split = 'character', output_mode = 'int', output_sequence_length = 10)
preprocess.adapt(raw_dataset)

In [9]:
preprocess.get_vocabulary(), preprocess.vocabulary_size()

(['',
  '[UNK]',
  'C',
  '=',
  'O',
  ')',
  '(',
  '1',
  '\n',
  'N',
  'F',
  ']',
  '[',
  '-',
  'S',
  '+',
  'l',
  '2',
  'r',
  'B',
  'I',
  'H',
  '#'],
 23)

In [10]:
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout
model = tf.keras.Sequential([Embedding(input_dim = len(preprocess.get_vocabulary()),output_dim = 100),
                             LSTM(64, dropout = 0.1, recurrent_dropout = 0.1, return_sequences = True),
                             Dropout(0.5), Dense(len(preprocess.get_vocabulary()))])

model.compile(optimizer = 'adam', loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits = True), metrics = ['accuracy'])

In [12]:
trn_features = preprocess(features)
trn_labels = preprocess(labels)
trn_features

<tf.Tensor: shape=(4994, 10), dtype=int64, numpy=
array([[2, 2, 6, ..., 2, 7, 3],
       [2, 6, 3, ..., 7, 3, 2],
       [6, 3, 4, ..., 3, 2, 2],
       ...,
       [6, 3, 4, ..., 6, 3, 4],
       [3, 4, 5, ..., 3, 4, 5],
       [4, 5, 4, ..., 4, 5, 4]], dtype=int64)>

In [13]:
trn_labels

<tf.Tensor: shape=(4994, 10), dtype=int64, numpy=
array([[2, 6, 3, ..., 7, 3, 2],
       [6, 3, 4, ..., 3, 2, 2],
       [3, 4, 5, ..., 2, 2, 3],
       ...,
       [3, 4, 5, ..., 3, 4, 5],
       [4, 5, 4, ..., 4, 5, 4],
       [5, 4, 5, ..., 5, 4, 8]], dtype=int64)>

In [14]:
model.fit(trn_features, trn_labels, epochs = 10) 

Epoch 1/10
157/157 [==============================] - 14s 42ms/step - loss: 2.0783 - accuracy: 0.3636
Epoch 2/10
157/157 [==============================] - 6s 41ms/step - loss: 1.2450 - accuracy: 0.5857
Epoch 3/10
157/157 [==============================] - 5s 33ms/step - loss: 1.0423 - accuracy: 0.6561
Epoch 4/10
157/157 [==============================] - 5s 33ms/step - loss: 0.9443 - accuracy: 0.6878
Epoch 5/10
157/157 [==============================] - 5s 33ms/step - loss: 0.8810 - accuracy: 0.7049
Epoch 6/10
157/157 [==============================] - 5s 33ms/step - loss: 0.8425 - accuracy: 0.7183
Epoch 7/10
157/157 [==============================] - 5s 33ms/step - loss: 0.8120 - accuracy: 0.7251
Epoch 8/10
157/157 [==============================] - 5s 34ms/step - loss: 0.7902 - accuracy: 0.7295
Epoch 9/10
157/157 [==============================] - 5s 33ms/step - loss: 0.7743 - accuracy: 0.7350
Epoch 10/10
157/157 [==============================] - 8s 51ms/step - loss: 0.7588 - accur